version: "3.8"

services:

  backend:
    image: dandart/item-manager-backend
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - 8081:8081

  frontend:
    image: dandart/item-manager-frontend
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - 8080:8080